import 'package:flutter/material.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedEllipse1Widget1.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedGroup35Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedGroup55Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedLine2Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedEllipse2Widget1.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedGroup56Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedGroup71Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedGroup63Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedGroup70Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedImage2Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedGroup69Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedGroup93Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedRectangle5Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedLine1Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedGroup54Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedGroup68Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedParWidget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedGroup64Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedHole5Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedRectangle8Widget.dart';
import 'package:golfcandie/methewapp/generatedscreen2widget/generated/GeneratedGroup27Widget.dart';

import 'generated/GeneratedEllipse1Widget.dart';

/* Frame Screen2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(32.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return Container(
            height: 926.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 428.0,
                    height: 926.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(32.0),
                    ),
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,

                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.circular(32.0),
                            child: Container(
                              color: Color.fromARGB(255, 255, 255, 255),
                            ),
                          ),
                          Positioned(
                            left: 24.0,
                            top: 25.0,
                            right: null,
                            bottom: null,
                            width: 50.0,
                            height: 50.0,
                            child: GestureDetector(
                              onTap: (){
                                Navigator.pop(context);
                              },
                              child: TopBackButton(),
                            ),
                          ),
                          Positioned(
                            left: 334.0,
                            top: 25.0,
                            right: null,
                            bottom: null,
                            width: 50.0,
                            height: 50.018394470214844,
                            child: GestureDetector(
                              onTap: (){
                                Navigator.pop(context);
                              },
                              child: DotsTopButton(),
                            )
                          ),
                          Positioned(
                            left: 24.0,
                            top: 684.0,
                            right: null,
                            bottom: null,
                            width: 380.0,
                            height: 92.0,
                            child: GestureDetector(
                              onTap: (){
                                Navigator.pushNamed(context, "/GeneratedScreen3Widget");
                              },
                              child: BottomBarGreen(),
                            )
                          ),
                          Positioned(
                            left: 154.0,
                            top: 31.0,
                            right: null,
                            bottom: null,
                            width: 109.0,
                            height: 40.0,
                            child: GeneratedHole5Widget(),
                          ),
                          Positioned(
                            left: 0,
                            top: 141.0,
                            right: null,
                            bottom: null,
                            width: 300,
                            height: 550.1187744140625,
                            child: GroundMapImage(),
                          ),
                          Positioned(
                            left: 260.0,
                            top: 88.0,
                            right: null,
                            bottom: null,
                            width: 125.0,
                            height: 119.0,
                            child: TopRemainWidget(),
                          ),
                          Positioned(
                            left: 260.0,
                            top: 403.0,
                            right: null,
                            bottom: null,
                            width: 100.0,
                            height: 100.0,
                            child: MiddleMphWidget(),
                          ),
                          Positioned(
                            left: 60.0,
                            top: 474.0,
                            right: null,
                            bottom: null,
                            width: 24.0,
                            height: 24.0,
                            child: GeneratedEllipse2Widget1(),
                          ),
                          Positioned(
                            left: 160.0,
                            top: 385.0,
                            right: null,
                            bottom: null,
                            width: 126.21100616455078,
                            height: 0.0,
                            child: GeneratedLine1Widget(),
                          ),
                          Positioned(
                            left: 70,
                            top: 470,
                            right: null,
                            bottom: null,
                            width: 198.22613525390625,
                            height: 0.0,
                            child: GeneratedLine2Widget(),
                          ),
                          Positioned(
                            left: 190.0,
                            top: 550.0,
                            right: null,
                            bottom: null,
                            width: 238.0,
                            height: 73.0,
                            child: GestureDetector(
                              onTap: (){
                                Navigator.pushNamed(context, "/GeneratedScreen3Widget");
                              },
                              child: GeneratedRectangle8Widget(),
                            )
                          ),
                        ]),
                  ))
            ]));
      }),
    ));
  }
}
